{
 "title": "Counters",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Redirections",
   "type": "stat",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "contador.redirect" }
   ]
  },
  {
   "title": "QR",
   "type": "stat",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "contador.qr" }
   ]
  },
  {
   "title": "QR Metro Rivas",
   "type": "stat",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "contador.qr-metro" }
   ]
  },
  {
   "title": "Redirections",
   "type": "graph",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "contador.redirect" }
   ]
  },
  {
   "title": "QR",
   "type": "graph",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "contador.qr" }
   ]
  },
  {
   "title": "QR Metro Rivas",
   "type": "graph",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "contador.qr-metro" }
   ]
  },
  {
   "title": "Redirections",
   "type": "graph",
   "description": "From domain sign.unconditionalbasicincome.eu",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "contador.redirect-increment" }
   ]
  }
 ]
}