{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 4,
  "iteration": 1604092303720,
  "links": [],
  "panels": [
    {
      "cacheTimeout": "",
      "datasource": "Graphite",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null
          },
          "mappings": [],
          "max": 1000000,
          "min": 0,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "dark-purple",
                "value": null
              },
              {
                "color": "semi-dark-blue",
                "value": 50000
              },
              {
                "color": "semi-dark-green",
                "value": 150000
              },
              {
                "color": "yellow",
                "value": 300000
              },
              {
                "color": "dark-orange",
                "value": 600000
              },
              {
                "color": "red",
                "value": 900000
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 7,
        "x": 9,
        "y": 0
      },
      "hideTimeOverride": false,
      "id": 4,
      "maxDataPoints": 10000,
      "options": {
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "7.1.5",
      "repeat": null,
      "targets": [
        {
          "refCount": 0,
          "refId": "B",
          "target": "sumSeries(eci.unconditionalbasicincome.*)"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Total",
      "transformations": [
        {
          "id": "labelsToFields",
          "options": {}
        }
      ],
      "transparent": true,
      "type": "gauge"
    },
    {
      "aliasColors": {
        "Bulgaria": "dark-purple",
        "France": "dark-blue",
        "Germany": "orange",
        "Greece": "light-blue",
        "Hungary": "dark-green",
        "Italy": "yellow",
        "Netherlands": "light-purple",
        "Slovenia": "light-green",
        "Spain": "red"
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "decimals": 0,
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": []
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 3,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 7
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refCount": 0,
          "refId": "A",
          "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(eci.unconditionalbasicincome.$Country, 'eci.unconditionalbasicincome.at', 'Austria'), 'eci.unconditionalbasicincome.be', 'Belgium'), 'eci.unconditionalbasicincome.bg', 'Bulgaria'), 'eci.unconditionalbasicincome.cy', 'Cyprus'), 'eci.unconditionalbasicincome.cz', 'Czech Republic'), 'eci.unconditionalbasicincome.de', 'Germany'), 'eci.unconditionalbasicincome.dk', 'Denmark'), 'eci.unconditionalbasicincome.ee', 'Estonia'), 'eci.unconditionalbasicincome.es', 'Spain'), 'eci.unconditionalbasicincome.fi', 'Finland'), 'eci.unconditionalbasicincome.fr', 'France'), 'eci.unconditionalbasicincome.gr', 'Greece'), 'eci.unconditionalbasicincome.hr', 'Croatia'), 'eci.unconditionalbasicincome.hu', 'Hungary'), 'eci.unconditionalbasicincome.ie', 'Ireland'), 'eci.unconditionalbasicincome.it', 'Italy'), 'eci.unconditionalbasicincome.lt', 'Lithuania'), 'eci.unconditionalbasicincome.lu', 'Luxembourg'), 'eci.unconditionalbasicincome.lv', 'Latvia'), 'eci.unconditionalbasicincome.mt', 'Malta'), 'eci.unconditionalbasicincome.nl', 'Netherlands'), 'eci.unconditionalbasicincome.pl', 'Poland'), 'eci.unconditionalbasicincome.pt', 'Portugal'), 'eci.unconditionalbasicincome.ro', 'Romania'), 'eci.unconditionalbasicincome.se', 'Sweden'), 'eci.unconditionalbasicincome.si', 'Slovenia'), 'eci.unconditionalbasicincome.sk', 'Slovakia')",
          "textEditor": true
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "By Country",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "decimals": 0,
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "decimals": 0,
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {},
      "bars": false,
      "cacheTimeout": "",
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "decimals": 0,
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": [],
          "unit": "none"
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 3,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 7
      },
      "hiddenSeries": false,
      "id": 5,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "hideZero": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "maxDataPoints": 10000,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "target": "alias(sumSeries(eci.unconditionalbasicincome.*, *), 'Total')"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Total",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "decimals": 0,
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {
        "Bulgaria": "dark-purple",
        "France": "dark-blue",
        "Germany": "orange",
        "Greece": "light-blue",
        "Hungary": "dark-green",
        "Italy": "yellow",
        "Netherlands": "light-purple",
        "Slovenia": "light-green",
        "Spain": "red"
      },
      "bars": true,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "decimals": 0,
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": []
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 3,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 16
      },
      "hiddenSeries": false,
      "id": 6,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "max": true,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": true,
      "targets": [
        {
          "refCount": 0,
          "refId": "B",
          "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(eci.increments.$Country, 'eci.increments.at', 'Austria'), 'eci.increments.be', 'Belgium'), 'eci.increments.bg', 'Bulgaria'), 'eci.increments.cy', 'Cyprus'), 'eci.increments.cz', 'Czech Republic'), 'eci.increments.de', 'Germany'), 'eci.increments.dk', 'Denmark'), 'eci.increments.ee', 'Estonia'), 'eci.increments.es', 'Spain'), 'eci.increments.fi', 'Finland'), 'eci.increments.fr', 'France'), 'eci.increments.gr', 'Greece'), 'eci.increments.hr', 'Croatia'), 'eci.increments.hu', 'Hungary'), 'eci.increments.ie', 'Ireland'), 'eci.increments.it', 'Italy'), 'eci.increments.lt', 'Lithuania'), 'eci.increments.lu', 'Luxembourg'), 'eci.increments.lv', 'Latvia'), 'eci.increments.mt', 'Malta'), 'eci.increments.nl', 'Netherlands'), 'eci.increments.pl', 'Poland'), 'eci.increments.pt', 'Portugal'), 'eci.increments.ro', 'Romania'), 'eci.increments.se', 'Sweden'), 'eci.increments.si', 'Slovenia'), 'eci.increments.sk', 'Slovakia')",
          "textEditor": true
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Signatures per day",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "decimals": 0,
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "decimals": 0,
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {},
      "bars": true,
      "cacheTimeout": "",
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "decimals": 0,
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": [],
          "unit": "none"
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 3,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 16
      },
      "hiddenSeries": false,
      "id": 7,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "hideZero": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "maxDataPoints": 10000,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": true,
      "targets": [
        {
          "refId": "A",
          "target": "alias(sumSeries(eci.increments.*, *), 'Total')"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Total per day",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "decimals": 0,
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": false,
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": "",
        "current": {
          "selected": true,
          "text": [
            "at",
            "be",
            "bg",
            "cy",
            "cz",
            "de",
            "dk",
            "ee",
            "es",
            "fi",
            "fr",
            "gr",
            "hr",
            "hu",
            "ie",
            "it",
            "lt",
            "lu",
            "lv",
            "mt",
            "nl",
            "pl",
            "pt",
            "ro",
            "se",
            "si",
            "sk"
          ],
          "value": [
            "at",
            "be",
            "bg",
            "cy",
            "cz",
            "de",
            "dk",
            "ee",
            "es",
            "fi",
            "fr",
            "gr",
            "hr",
            "hu",
            "ie",
            "it",
            "lt",
            "lu",
            "lv",
            "mt",
            "nl",
            "pl",
            "pt",
            "ro",
            "se",
            "si",
            "sk"
          ]
        },
        "datasource": "Graphite",
        "definition": "eci.unconditionalbasicincome.*",
        "hide": 0,
        "includeAll": false,
        "label": "Country",
        "multi": true,
        "name": "Country",
        "options": [],
        "query": "eci.unconditionalbasicincome.*",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "2020-09-24T20:00:00.000Z",
    "to": "now-1m"
  },
  "timepicker": {
    "nowDelay": "1m",
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "European Citizen's Initiative for Unconditional Basic Income",
  "uid": "Zua6l34Zgz1",
  "version": 29
}
