{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 3,
  "iteration": 1600401710209,
  "links": [],
  "panels": [
    {
      "datasource": "Graphite",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null
          },
          "mappings": [],
          "max": 1000000,
          "min": 0,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "dark-purple",
                "value": null
              },
              {
                "color": "semi-dark-blue",
                "value": 50000
              },
              {
                "color": "semi-dark-green",
                "value": 150000
              },
              {
                "color": "yellow",
                "value": 350000
              },
              {
                "color": "dark-orange",
                "value": 650000
              },
              {
                "color": "red",
                "value": 800000
              }
            ]
          },
          "unit": "none"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 7,
        "x": 9,
        "y": 0
      },
      "id": 4,
      "options": {
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "7.1.5",
      "repeat": null,
      "targets": [
        {
          "refCount": 0,
          "refId": "B",
          "target": "sumSeries(eci.finning.*)"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Total",
      "transformations": [
        {
          "id": "labelsToFields",
          "options": {}
        }
      ],
      "transparent": true,
      "type": "gauge"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": []
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 1,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 7
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refCount": 0,
          "refId": "A",
          "target": "aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(aliasSub(eci.finning.$Country, 'eci.finning.at', 'Austria'), 'eci.finning.be', 'Belgium'), 'eci.finning.bg', 'Bulgaria'), 'eci.finning.cy', 'Cyprus'), 'eci.finning.cz', 'Czech Republic'), 'eci.finning.de', 'Germany'), 'eci.finning.dk', 'Denmark'), 'eci.finning.ee', 'Estonia'), 'eci.finning.es', 'Spain'), 'eci.finning.fi', 'Finland'), 'eci.finning.fr', 'France'), 'eci.finning.gr', 'United Kingdom'), 'eci.finning.hr', 'Croatia'), 'eci.finning.hu', 'Hungary'), 'eci.finning.ie', 'Ireland'), 'eci.finning.it', 'Italy'), 'eci.finning.lt', 'Lithuania'), 'eci.finning.lu', 'Luxembourg'), 'eci.finning.lv', 'Latvia'), 'eci.finning.mt', 'Malta'), 'eci.finning.nl', 'Netherlands'), 'eci.finning.pl', 'Poland'), 'eci.finning.pt', 'Portugal'), 'eci.finning.ro', 'Romania'), 'eci.finning.se', 'Sweden'), 'eci.finning.si', 'Slovenia'), 'eci.finning.sk', 'Slovakia')",
          "textEditor": false
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "By Country",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "Graphite",
      "decimals": 0,
      "fieldConfig": {
        "defaults": {
          "custom": {},
          "links": [],
          "unit": "none"
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 1,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 7
      },
      "hiddenSeries": false,
      "id": 5,
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": true,
        "hideEmpty": false,
        "hideZero": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "sideWidth": 250,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "connected",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {}
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "target": "alias(sumSeries(eci.finning.*, *), 'Total')"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Total",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "transformations": [],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "decimals": 0,
          "format": "none",
          "label": "Number of Signatures",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "30s",
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": "",
        "current": {
          "selected": true,
          "text": [
            "at",
            "be",
            "bg",
            "cy",
            "cz",
            "de",
            "dk",
            "ee",
            "es",
            "fi",
            "fr",
            "gr",
            "hr",
            "hu",
            "ie",
            "it",
            "lt",
            "lu",
            "lv",
            "mt",
            "nl",
            "pl",
            "pt",
            "ro",
            "se",
            "si",
            "sk"
          ],
          "value": [
            "at",
            "be",
            "bg",
            "cy",
            "cz",
            "de",
            "dk",
            "ee",
            "es",
            "fi",
            "fr",
            "gr",
            "hr",
            "hu",
            "ie",
            "it",
            "lt",
            "lu",
            "lv",
            "mt",
            "nl",
            "pl",
            "pt",
            "ro",
            "se",
            "si",
            "sk"
          ]
        },
        "datasource": "Graphite",
        "definition": "eci.finning.*",
        "hide": 0,
        "includeAll": false,
        "label": "Country",
        "multi": true,
        "name": "Country",
        "options": [],
        "query": "eci.finning.*",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-2d",
    "to": "now-1m"
  },
  "timepicker": {
    "nowDelay": "1m",
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "ECI Signatures",
  "uid": "Zua6l34Zgz",
  "version": 6
}
